CREATE TABLE SERIE_TRES (
  ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  LIMITE NUMBER NOT NULL,
  RESULTADO NUMBER NOT NULL,
  FECHA DATE DEFAULT SYSDATE
);

COMMIT;

-- ? Paso 4. Crear un Stored Procedure
-- El procedimiento almacenará la información calculada desde Java.

CREATE OR REPLACE PROCEDURE SP_GUARDAR_SERIE_TRES (
    P_LIMITE IN NUMBER,
    P_RESULTADO IN NUMBER
) AS
BEGIN
    INSERT INTO SERIE_TRES (LIMITE, RESULTADO)
    VALUES (P_LIMITE, P_RESULTADO);

    COMMIT;
END;
/

COMMIT;